### ISSUE TITLE
Hit and miss with pdf format for taxes

### ISSUE THREAD

**Issue by HaAdolfo** [grantmakers/grantmakers.github.io#29]
PDF format for taxes is a hit-and-miss sometimes especially for 2016 tax returns for Foundations.
However it works well for 2015 tax returns in pdf format.
Here is one example of hit-and-miss pdf (2016) for Ina Kay Foundation, Inc.
![nopdfformat](https://user-images.githubusercontent.com/33579595/32796692-5b130ff6-c924-11e7-8cd0-1627533580e2.jpg)

**Comment by chadokruse** [comment]
Appreciate the continued great bug reporting Ha!

There's an apparent lag between when the IRS releases the electronic filings and when the PDF images appear on Foundation Center (the current source for the PDF images).

The good news is this is already on the near-term roadmap ([see this issue](https://github.com/grantmakers/profiles/issues/3)).
