### ISSUE TITLE
Change definition of "Has Recent Grants"

### ISSUE THREAD

**Issue by chadokruse** [grantmakers/grantmakers.github.io#34]
Has Recent Grants is true if the organization's most recent electronically filed 990PF has any grants.

Need to consider organizations that used to file electronically, but no longer do (e.g. should grants from tax year 2015 really be considered as "recent"?).

Particularly important as more foundations move to DAFs (e.g. EIN 452523468)

See normalize.js

**Comment by HaAdolfo** [comment]
Typically medium or large organizations file 990PF electronically. When we are searching for grants from foundations, we usually see their 990s. If some foundations are no longer filing their 990 electronically, we would not consider searching for their grants, as they are "winding down", or their assets are very small.

**Comment by chadokruse** [comment]
Great insight @HaAdolfo.

**Comment by chadokruse** [comment]
Long term the hasRecentGrants definition will be removed completely as it's only a proxy for if a foundation is still active or not. In its place we will cross-check the more definitive sources of this info (e.g. Pub 78 or the EO MBF).

For now, changing the definition to be equal to any profiles whose latest tax filing is two years prior or newer (e.g. for the 2019 calendar year, hasRecentGrants will be true if the foundation's latest filing is 2017 or later).

Future discussions will take place here: #49
